spring.application.name=chat-app
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operations-sorter=alpha
#springdoc.swagger-ui.url=/openapi.yaml

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.session.store-type=redis
spring.session.timeout=30m
spring.session.redis.namespace=myapp:session

spring.datasource.url=jdbc:postgresql://ep-silent-glade-ab7iz4ip-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_a0MQZtoi5nYb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect